[package]
name = "zinc_oxide"
version = "0.1.4"
authors = ["Amadeus Mader <amadeus@mozart409.com"]
categories = ["command-line-utilities"]
edition = "2024"
exclude = ["/website"]
homepage = "https://zinc-oxide.mozart409.com"
keywords = ["git", "cli"]
license-file = "LICENSE"
publish = false
readme = "README.md"
repository = "https://github.com/Mozart409/zinc_oxide"
description = "A rust cli that checks recursively for git projects and reports their statuses"

[package.metadata.deb]
name = "zinc_oxide"
maintainer = "Amadeus Mader <amadeus@mozart409.com>"
copyright = "2025 Amadeus Mader"
license-file = ["LICENSE"]
section = "utility"
priority = "optional"

[package.metadata.generate-rpm]
license = "MIT"
assets = [
  { source = "target/release/zinc_oxide", dest = "/usr/bin/zinc_oxide", mode = "755" },
]

[dependencies]
color-eyre = { version = "0.6.5", default-features = false }
git2 = { version = "0.20.4", features = ["vendored-libgit2"] }
gumdrop = "0.8.1"

[features]
default = []
nix = []

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.8"
